services:
  php_codeigniter:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: codeigniter_php
    ports:
      - "${HTTP_PORT}:80"
    environment:
      VIRTUALHOST: ${VIRTUALHOST}
    ## tty: true
    ## working_dir: /var/www/html/
    volumes:
      - .:/var/www/html/
    networks:
      - codeigniter-network
    #restart: always
#  nginx_codeigniter:
#    depends_on:
#      - php_codeigniter
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile
#    container_name: codeigniter_nginx
#    tty: true
#    ports:
#      - "80:80"
#    networks:
#      - codeigniter-network
    #restart: always
networks:
  codeigniter-network:
    driver: bridge

